import { Item } from './redux/slices/inventorySlice';

export const defaultList: Item[] = [
  {
    name: 'COSRX - Advanced Snail 96 Mucin Power Essence',
    ingredients: [
      'Snail Secretion Filtrate',
      'Betaine',
      'Butylene Glycol',
      '1,2-Hexanediol',
      'Sodium Polyacrylate',
      'Phenoxyethanol',
      'Sodium Hyaluronate',
      'Allantoin',
      'Ethyl Hexanediol',
      'Carbomer',
      'Panthenol',
      'Arginine',
    ],
  },
  {
    name: 'Dear, Klairs - Freshly Juiced Vitamin Drop',
    ingredients: [
      'Water',
      'Propylen Glycol',
      'Ascorbic Acid',
      'Hydroxyethylcellulose',
      'Centella Asiatica Extract',
      'Citrus Junos Fruit Extract',
      'Illicium Verum(Anise) Fruit Extract',
      'Citrus Paradisi(Grapefruit) Fruit Extract',
      'Nelumbium Speciosum Flower Extract',
      'Paeonia Suffruticosa Root Extract',
      'Scutellaria Baicalensis Root Extract',
      'Polysorbate 60',
      'Brassica Oleracea Italica (Broccoli) Extract',
      'Chaenomeles Sinensis Fruit Extract',
      'Citrus Aurantium Dulcis (Orange) Oil',
      'Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer',
      'Disodium EDTA',
      'Lavandula Angustifolia (Lavender) Oil',
      'Camellia Sinensis Callus Culture Extract',
      'Larix Europaea Wood Extract',
      'Chrysanthellum Indicum Extract',
      'Rheum Palmatum Root Extract',
      'Asarum Sieboldi Root Extract',
      'Quercus Mongolia Leaf Extract',
      'Persicaria Hydropiper Extract',
      'Corydalis Turtschaninovii Root Extract',
      'Coptis Chinensis Root Extract',
      'Magnolia Obovata Bark Extract',
      'Lysine HCL',
      'Proline',
      'Sodium Ascorbyl Phosphate',
      'Acetyl Methionine',
      'Theanine',
      'Lecithin',
      'Acetyl Glutamine',
      'SH-Olgopeptide-1',
      'SH-Olgopeptide-2',
      'SH-Polypeptide-1',
      'SH-Polypeptide-9',
      'SH-Polypeptide-11',
      'Bacillus/Soybean/Folic Acid Ferment Extract',
      'Sodium Hyaluronate',
      'Caprylyl Glycol',
      'Butylene Glycol',
      '1,2-Hexanediol',
      'Limonene',
    ],
  },
  {
    name: 'COSRX - The Retinol 0.5 Oil',
    ingredients: [
      'Squalane',
      'Glycine Soja (Soybean) Oil',
      'Di-C12-13 Alkyl Malate',
      'Retinol',
      'Caprylic/Capric Triglyceride',
      'BHT',
      'Tocotrienols',
      'Tocopherol',
      'Elaeis Guineensis (Palm) Oil',
      'Hydroxymethoxyphenyl Decanone',
    ],
  },
  {
    name: 'Beauty of Joseon - Glow Serum',
    ingredients: [
      'Propolis Extract',
      'Dipropylene Glycol',
      'Glycerin',
      'Butylene Glycol',
      'Water',
      'Niacinamide',
      '1,2-Hexanediol',
      'Melia Azadirachta Flower Extract',
      'Melia Azadirachta Leaf Extract',
      'Sodium Hyaluronate',
      'Curcuma Longa (Turmeric) Root Extract',
      'Ocimum Sanctum Leaf Extract',
      'Theobroma Cacao (Cocoa) Seed Extract',
      'Melaleuca Alternifolia (Tea Tree) Extract',
      'Centella Asiatica Extract',
      'Corallina Officinalis Extract',
      'Lotus Corniculatus Seed Extract',
      'Calophyllum Inophyllum Seed Oil',
      'Betaine Salicylate',
      'Sodium Polyacryloyldimethyl Taurate',
      'Tromethamine',
      'Polyglyceryl-10 Laurate',
      'Caprylyl Glycol',
      'Ethylhexylglycerin',
      'Dextrin',
      'Pentylene Glycol',
      'Octanediol',
      'Tocopherol',
      'Xanthan Gum',
      'Carbomer',
    ],
  },
  {
    name: 'Beauty of Joseon - Dynasty Cream',
    ingredients: [
      'Water',
      'Oryza Sativa (Rice) Bran Water',
      'Glycerin',
      'Panax Ginseng Root Water',
      'Hydrogenated Polydecene',
      '1,2-Hexanediol',
      'Niacinamide',
      'Squalane',
      'Butylene Glycol',
      'Propanediol',
      'Dicaprylate/Dicaprate',
      'Cetearyl Olivate',
      'Sorbitan Olivate',
      'Ammonium Acryloyldimethyltaurate/VP Copolymer',
      'Xanthan Gum',
      'Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
      'Tromethamine',
      'Carthamus Tinctorius (Safflower) Seed Oil',
      'Hydrogenated Coconut Oil',
      'Glyceryl Acrylate/Acrylic Acid Copolymer',
      'Ethylhexylglycerin',
      'Adenosine',
      'Caprylic/Capric Triglyceride',
      'Disodium EDTA',
      'Hyaluronic Acid',
      'Hydrolyzed Hyaluronic Acid',
      'Sodium Hyaluronate',
      'Honey Extract',
      'Ceramide NP',
      'Hydrogenated Lecithin',
      'Coptis Japonica Root Extract',
      'Raphanus Sativus (Radish) Seed Extract',
      'Lycium Chinense Fruit Extract',
      'Theobroma Cacao (Cocoa) Seed Extract',
      'Phellinus Linteus Extract',
      'Dextrin',
      'Scutellaria Baicalensis Root Extract',
    ],
  },
  {
    name: 'SOME BY MI - AHA, BHA, PHA 30 Days Miracle Toner 150ml',
    ingredients: [
      'Water',
      'Butylene Glycol',
      'Dipropylene Glycol',
      'Glycerin',
      'Niacinamide',
      'Melaleuca Alternifolia (Tea Tree) Leaf Extract (10000ppm)',
      'Polyglyceryl-4 Caprate',
      'Carica Papaya (Papaya) Fruit Extract',
      'Lens Esculenta (Lentil) Seed Extract',
      'Hamamelis Virginiana (Witch Hazel) Extract',
      'Nelumbo Nucifera (Sacred Lotus) Flower Extract',
      'Swiftlet Nest Extract',
      'Sodium Hyaluronate',
      'Fructan',
      'Allantoin',
      'Adenosine',
      'Hydroxyethyl Urea',
      'Xylitol',
      'Salicylic Acid (100ppm)',
      'Lactobionic Acid (100ppm)',
      'Citric Acid (500ppm)',
      'Sodium Citrate',
      '1,2-Hexanediol',
      'Benzyl Glycol',
      'Ethylhexylglycerin',
      'Raspberry Ketone',
      'Mentha Piperita (Peppermint) Oil',
    ],
  },
  {
    name: 'Beauty of Joseon - Ginseng Essence Water',
    ingredients: [
      'Panax Ginseng Root Water',
      'Butylene Glycol',
      'Glycerin',
      'Propanediol',
      'Niacinamide',
      '1,2-Hexanediol',
      'Water',
      'Hydroxyacetophenone',
      'Glyceryl Glucoside',
      'Xanthna Gum',
      'Panthenol',
      'Dipotassium Glycyrrhizate',
      'Allantoin',
      'Adenosine',
      'Panax Ginseng Callus Culture Extract',
      'Theobroma Cacao(Cocoa) Extract',
      'Dextrin',
      'Glucose',
      'Panax Ginseng Root Extract',
      'Panax Ginseng Berry Extract',
      'Lactobacillus/Panax Ginseng Root Ferment Filtrate',
      'Sodium Hyaluronate',
      'Ethylhexyglycerin',
      'Disodium EDTA',
    ],
  },
];
