export interface iIngredient {
  name: string;
  avoid: string[];
}

export const ingredients: iIngredient[] = [
  {
    name: 'retinol',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'retinaldehyde',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'retinyl esters',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'tretinoin',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'adapalene',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'tazarotene',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'trifarotene',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
      'benzoyl peroxide',
      'alpha hydroxy acid',
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
      'beta hydroxy acid',
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'benzoyl peroxide',
    avoid: [
      'retinol',
      'retinaldehyde',
      'retinyl esters',
      'tretinoin',
      'adapalene',
      'tazarotene',
      'trifarotene',
    ],
  },
  {
    name: 'niacinamide',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
    ],
  },
  {
    name: 'alpha hydroxy acid',
    avoid: [
      'lactic acid',
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
    ],
  },
  {
    name: 'lactic acid',
    avoid: [
      'glycolic acid',
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
    ],
  },
  {
    name: 'glycolic acid',
    avoid: [
      'malic acid',
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
    ],
  },
  {
    name: 'malic acid',
    avoid: [
      'citric acid',
      'tartaric acid',
      'hydroxycaprylic acid',
      'hydroxycapric acid',
    ],
  },
  {
    name: 'citric acid',
    avoid: ['tartaric acid', 'hydroxycaprylic acid', 'hydroxycapric acid'],
  },
  {
    name: 'tartaric acid',
    avoid: ['hydroxycaprylic acid', 'hydroxycapric acid'],
  },
  {
    name: 'hydroxycaprylic acid',
    avoid: ['hydroxycapric acid'],
  },
  {
    name: 'beta hydroxy acid',
    avoid: [
      'beta hydroxybutanoic acid',
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'beta hydroxybutanoic acid',
    avoid: [
      'tropic acid',
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'tropic acid',
    avoid: [
      'trethocanic acid',
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'trethocanic acid',
    avoid: [
      'salicylic acid',
      'salicylate',
      'sodium salicylate',
      'willow bark extract',
    ],
  },
  {
    name: 'salicylic acid',
    avoid: ['salicylate', 'sodium salicylate', 'willow bark extract'],
  },
  {
    name: 'salicylate',
    avoid: ['sodium salicylate', 'willow bark extract'],
  },
  {
    name: 'sodium salicylate',
    avoid: ['willow bark extract'],
  },
  {
    name: 'copper peptides',
    avoid: [
      'vitamin c',
      'l-ascorbic acid',
      'ascorbic acid',
      'ascorbyl glucoside',
    ],
  },
];
